[project]
name = "spark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyiceberg[duckdb,pyarrow]>=0.9.0",
    "pyspark[connect,sql]>=4.0.0",
    "soli-data-generator>=0.1.0",
    "sqlalchemy>=2.0.41",
]
