gateways:
  local:
    connection:
      type: duckdb
      register_comments: True
      pre_ping: False
      pretty_sql: True
      extensions:
        - httpfs
        - iceberg
        - aws
      secrets:
        - type: s3
          region: "us-east-1"
          key_id: "admin"
          secret: "password"
          endpoint: "http://localhost:9000"
          url_style: "path"
    state_connection:
      type: duckdb
      database: 'sqlmesh_state.db'
  
  spark:
    connection:
      type: spark
      config:
        spark.master: sc://localhost:15002
    test_connection:
      type: spark
      config:
        spark.master: sc://localhost:15002
        spark.sql.adaptive.coalescePartitions.enabled: true
    state_connection:
      type: duckdb
      database: 'sqlmesh_spark_state.db'
  
  prod:
    connection:
      type: postgres
      host: localhost
      port: 5432
      user: admin 
      password: password
      database: iceberg
      register_comments: True
      pre_ping: False
      pretty_sql: True
    state_connection:
      type: postgres
      host: localhost
      port: 5432
      user: admin
      password: password
      database: sqlmesh 

default_gateway: spark

model_defaults:
  dialect: spark

ignore_patterns:
  - "generator"