gateways:
  local:
    connection:
      type: duckdb
      database: 'dev.db'
      register_comments: True
      pre_ping: False
      pretty_sql: True
      extensions:
        - httpfs
        - iceberg
        - aws
    state_connection:
      type: duckdb
      database: 'sqlmesh_state.db'
  
  spark:
    connection:
      dialect: spark
      type: spark
      config:
        spark.master: spark://spark-master:7077
        spark.sql.catalog.iceberg: org.apache.iceberg.spark.SparkCatalog
        spark.sql.defaultCatalog: iceberg
        spark.sql.catalog.iceberg.type: rest
        spark.sql.catalog.iceberg.uri: http://spark-rest:8181
        spark.sql.catalog.iceberg.warehouse: s3://data/wh
        spark.sql.catalog.iceberg.s3.endpoint: http://minio:9000
        spark.sql.catalog.iceberg.s3.access-key: admin
        spark.sql.catalog.iceberg.s3.secret-key: password
        spark.sql.catalog.iceberg.s3.region: us-east-1
        spark.hadoop.fs.s3.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
        spark.hadoop.fs.s3a.access.key: admin
        spark.hadoop.fs.s3a.secret.key: password
        spark.hadoop.fs.s3a.endpoint: http://minio:9000
        spark.hadoop.fs.s3a.region: us-east-1
        spark.hadoop.fs.s3a.path.style.access: true
        spark.hadoop.fs.s3a.connection.ssl.enabled: false
        spark.sql.extensions: org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
    state_connection:
      type: duckdb
      database: 'sqlmesh_spark_state.db'
  
  prod:
    connection:
      type: postgres
      host: {{ env_var('PG_HOST') }}
      port: {{ env_var('PG_PORT') }}
      user: {{ env_var('PG_USER') }}
      password: {{ env_var('PG_PASSWORD') }}
      database: postgres
      register_comments: True
      pre_ping: False
      pretty_sql: True
    state_connection:
      type: postgres
      host: {{ env_var('PG_HOST') }}
      port: {{ env_var('PG_PORT') }}
      user: {{ env_var('PG_USER') }}
      password: {{ env_var('PG_PASSWORD') }}
      database: postgres

default_gateway: local

model_defaults:
  dialect: duckdb

  # For Spark gateway, models can override with: dialect: spark

ignore_patterns:
  - "generator"