gateways:
  local:
    connection:
      type: duckdb
      register_comments: True
      pre_ping: False
      pretty_sql: True
      extensions:
        - httpfs
        - iceberg
        - aws
    state_connection:
      type: duckdb
      database: 'sqlmesh_state.db'
  
  spark:
    connection:
      type: spark
      config:
        spark.remote: sc://localhost:15002
        spark.sql.defaultCatalog: iceberg
        spark.sql.catalog.iceberg.type: rest 
        spark.sql.catalog.iceberg.uri: http://iceberg-rest:8181
        spark.sql.catalog.iceberg: org.apache.iceberg.spark.SparkCatalog
        spark.sql.catalog.iceberg.io-impl: org.apache.iceberg.aws.s3.S3FileIO
        spark.sql.catalog.iceberg.warehouse: s3a://iceberg/warehouse
        # AWS S3 credentials for MinIO
        spark.sql.catalog.iceberg.s3.access-key-id: admin
        spark.sql.catalog.iceberg.s3.secret-access-key: password
        spark.sql.catalog.iceberg.s3.endpoint: http://minio:9000
        spark.sql.catalog.iceberg.s3.path-style-access: true
    test_connection:
      type: spark
      config:
        spark.remote: sc://localhost:15002
        spark.sql.adaptive.coalescePartitions.enabled: true
    state_connection:
      type: postgres 
      database: sqlmesh
      host: localhost
      port: 5432
      user: admin
      password: password
  
  prod:
    connection:
      type: postgres
      host: localhost
      port: 5432
      user: admin 
      password: password
      database: iceberg
      register_comments: True
      pre_ping: False
      pretty_sql: True
    state_connection:
      type: postgres
      host: localhost
      port: 5432
      user: admin
      password: password
      database: sqlmesh 

default_gateway: spark

model_defaults:
  dialect: spark

ignore_patterns:
  - "generator"